/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package radiorelogio.view;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import radiorelogio.control.HoraControl;
import radiorelogio.control.MusicasControl;
import radiorelogio.control.ThreadHorario;

/**
 *
 * @author a1502727
 */
public class jMain extends javax.swing.JFrame {

    /**
     * Creates new form jMain
     */
//    public static MusicasTableModel modelo = new MusicasTableModel();
    public static DefaultTableModel modelo = new DefaultTableModel();
    public static MusicasControl musicas;
    public static HoraControl hora;
    public static boolean tocando, parar, falarHora;

    public jMain() {
        initComponents();
        setLocationRelativeTo(this);
        init();
    }

    private void init() {
        // Iniciando o relógio
        ThreadHorario relogio = new ThreadHorario();
        Thread tst = new Thread(relogio);
        tst.start();

        // Definindo o modelo da tabela
        jTblMusicas.setModel(modelo);
        modelo.addColumn("Título");
        modelo.addColumn("Tempo");
        jTblMusicas.getColumnModel().getColumn(0).setPreferredWidth(250);
        jTblMusicas.getColumnModel().getColumn(1).setPreferredWidth(15);

        // Criando o objeto que irá controlar as musicas
        musicas = new MusicasControl();
        
        //Craindo o objeto que irá controlar as horas
        hora = new HoraControl();

        // Definindo a flag de controle de tocando a playlist
        tocando = false;
        parar = false;
        
        // Definindo a flag para falar a hora cheia
        falarHora = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblMusicas = new javax.swing.JTable();
        jPnlHoras = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLblMinuto = new javax.swing.JLabel();
        jLblHora = new javax.swing.JLabel();
        jLblSegundos = new javax.swing.JLabel();
        jBtnAbrir = new javax.swing.JButton();
        jBtnRemover = new javax.swing.JButton();
        jBtnLimpar = new javax.swing.JButton();
        jBtnPlay = new javax.swing.JButton();
        jBtnParar = new javax.swing.JButton();
        jTxtOuvindo = new javax.swing.JTextField();
        jChkRepetirTudo = new javax.swing.JCheckBox();
        jChkRepetirUma = new javax.swing.JCheckBox();
        jBtnOuvirHora = new javax.swing.JButton();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTblMusicas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título"
            }
        ));
        jScrollPane1.setViewportView(jTblMusicas);

        jPnlHoras.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Arial", 0, 70)); // NOI18N
        jLabel1.setText(":");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 70)); // NOI18N
        jLabel2.setText(":");

        jLblMinuto.setFont(new java.awt.Font("Arial", 0, 70)); // NOI18N
        jLblMinuto.setText("00");

        jLblHora.setFont(new java.awt.Font("Arial", 0, 70)); // NOI18N
        jLblHora.setText("00");

        jLblSegundos.setFont(new java.awt.Font("Arial", 0, 70)); // NOI18N
        jLblSegundos.setText("00");

        javax.swing.GroupLayout jPnlHorasLayout = new javax.swing.GroupLayout(jPnlHoras);
        jPnlHoras.setLayout(jPnlHorasLayout);
        jPnlHorasLayout.setHorizontalGroup(
            jPnlHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlHorasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblHora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLblMinuto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLblSegundos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnlHorasLayout.setVerticalGroup(
            jPnlHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlHorasLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPnlHorasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLblMinuto)
                    .addComponent(jLabel2)
                    .addComponent(jLblHora)
                    .addComponent(jLblSegundos))
                .addContainerGap())
        );

        jBtnAbrir.setText("Abrir musicas...");
        jBtnAbrir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnAbrirMouseClicked(evt);
            }
        });

        jBtnRemover.setText("Remover musicas...");
        jBtnRemover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnRemoverMouseClicked(evt);
            }
        });

        jBtnLimpar.setText("Limpar Playlist");
        jBtnLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBtnLimparMouseClicked(evt);
            }
        });

        jBtnPlay.setText("PLAY");
        jBtnPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPlayActionPerformed(evt);
            }
        });

        jBtnParar.setText("PARAR");
        jBtnParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPararActionPerformed(evt);
            }
        });

        jTxtOuvindo.setEditable(false);

        jChkRepetirTudo.setText("Repetir tudo");
        jChkRepetirTudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkRepetirTudoActionPerformed(evt);
            }
        });

        jChkRepetirUma.setText("Repetir uma");
        jChkRepetirUma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jChkRepetirUmaActionPerformed(evt);
            }
        });

        jBtnOuvirHora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/images.jpg"))); // NOI18N
        jBtnOuvirHora.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBtnOuvirHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOuvirHoraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPnlHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnOuvirHora)
                        .addGap(140, 140, 140))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTxtOuvindo, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                .addComponent(jBtnPlay, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnParar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jChkRepetirTudo)
                                .addGap(18, 18, 18)
                                .addComponent(jChkRepetirUma)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBtnAbrir)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnRemover)
                                .addGap(18, 18, 18)
                                .addComponent(jBtnLimpar)))
                        .addContainerGap())))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBtnParar, jBtnPlay});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPnlHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnOuvirHora))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtOuvindo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnParar)
                    .addComponent(jBtnPlay))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnAbrir)
                    .addComponent(jBtnRemover)
                    .addComponent(jBtnLimpar)
                    .addComponent(jChkRepetirTudo)
                    .addComponent(jChkRepetirUma))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAbrirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnAbrirMouseClicked
        try {
            musicas.OpenFile();
        } catch (IOException ex) {
            Logger.getLogger(jMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnAbrirMouseClicked

    private void jBtnLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnLimparMouseClicked
        modelo.setNumRows(0);
        musicas.limparLista();
    }//GEN-LAST:event_jBtnLimparMouseClicked

    private void jBtnRemoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBtnRemoverMouseClicked
        int[] linhaSelecionada = jTblMusicas.getSelectedRows();

        if (linhaSelecionada.length > 0) {
            for (int i = (linhaSelecionada.length - 1); i >= 0; i--) {
                jMain.modelo.removeRow(linhaSelecionada[i]);
                musicas.removerMusica(linhaSelecionada[i]);
            }
        }
    }//GEN-LAST:event_jBtnRemoverMouseClicked

    private void jBtnPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPararActionPerformed
        musicas.stop();
    }//GEN-LAST:event_jBtnPararActionPerformed

    private void jBtnPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPlayActionPerformed
        musicas.play(jTblMusicas.getSelectedRow());
    }//GEN-LAST:event_jBtnPlayActionPerformed

    private void jChkRepetirTudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkRepetirTudoActionPerformed
        if(jChkRepetirUma.isSelected())
            jChkRepetirUma.setSelected(false);
    }//GEN-LAST:event_jChkRepetirTudoActionPerformed

    private void jChkRepetirUmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jChkRepetirUmaActionPerformed
        if(jChkRepetirTudo.isSelected())
            jChkRepetirTudo.setSelected(false);
    }//GEN-LAST:event_jChkRepetirUmaActionPerformed

    private void jBtnOuvirHoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOuvirHoraActionPerformed
        hora.iniciarThreadHoraAtual();
    }//GEN-LAST:event_jBtnOuvirHoraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jMain().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAbrir;
    private javax.swing.JButton jBtnLimpar;
    private javax.swing.JButton jBtnOuvirHora;
    private javax.swing.JButton jBtnParar;
    private javax.swing.JButton jBtnPlay;
    private javax.swing.JButton jBtnRemover;
    public static javax.swing.JCheckBox jChkRepetirTudo;
    public static javax.swing.JCheckBox jChkRepetirUma;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLblHora;
    public static javax.swing.JLabel jLblMinuto;
    public static javax.swing.JLabel jLblSegundos;
    public javax.swing.JPanel jPnlHoras;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTable jTblMusicas;
    public static javax.swing.JTextField jTxtOuvindo;
    // End of variables declaration//GEN-END:variables
}
